M48
; DRILL file {KiCad (6.0.7)} date Wed Oct  5 08:02:08 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-05T08:02:08-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1575
%
G90
G05
T1
X4.4108Y-4.815
X4.4108Y-5.265
T2
X4.1732Y-4.4488
X6.2795Y-4.4488
T0
M30
